dz_10/quotes/quoteapp/urls.py
from django.urls import path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name="main"),
    path('<int:page>', views.main, name="root_paginate"),
    path('tag/', views.tag, name="tag"),
    path('quote/', views.quote, name="quote"),
    path('author/', views.author, name="author"),
    path('detail_author/<int:quote_id>', views.detail_author, name="detail_author"),
    path('delete_quote/<int:quote_id>', views.delete_quote, name="delete_quote"),
    path('detail_tag/<int:quote_id>/', views.detail_tag, name='detail_tag'),
]

dz_10/quotes/quotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quoteapp.urls")),
   path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dz_10/quotes/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset_password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

dz_10/quotes/quoteapp/models.py
from django.db import models

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Tag(models.Model):
    name = models.CharField(max_length=100, null=False, unique=True)

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

dz_10/quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Tag, Author, Quote

class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']

class QuoteForm(ModelForm):

    quote = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    
    class Meta:
        model = Quote
        fields = ['quote', 'author']
        exclude = ['tags', 'created_at']

class AuthorForm(ModelForm):

    fullname = CharField(max_length=50)
    born_date = CharField(max_length=50)
    born_location = CharField(max_length=150)
    description = TextInput()

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']
        exclude = ['created_at']

dz_10/quotes/quoteapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from .models import Quote, Tag, Author
from .forms import TagForm, QuoteForm, AuthorForm
from django.contrib.auth.decorators import login_required

def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quoteapp/index.html', context={'quotes': quotes_on_page})

@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/tag.html', {'form': form})

    return render(request, 'quoteapp/tag.html', {'form': TagForm()})

@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/author.html', {'form': form})

    return render(request, 'quoteapp/author.html', {'form': AuthorForm()})

@login_required
def quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote=form.save(commit=False)
            author_id = request.POST.get('author')
            author = Author.objects.get(id=author_id)
            new_quote.author = author

            new_quote.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/quote.html', {"authors": authors, "tags":tags, 'form': form})

    return render(request, 'quoteapp/quote.html', {"authors": authors, "tags":tags, 'form': QuoteForm()})

def detail_author(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'quoteapp/detail_author.html', {"quote": quote})

@login_required
def delete_quote(request, quote_id):
    Quote.objects.get(pk=quote_id).delete()
    return redirect(to='quoteapp:main')

def detail_tag(request, quote_id):
    quotes = Quote.objects.filter(tags=quote_id)
    return render(request, 'quoteapp/detail_tag.html', {"quotes": quotes})

dz_10/quotes/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the fullname:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the born date:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the born location:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the description:
            {{form.description}}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

dz_10/quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}" />
    <title>homwork</title>
  </head>
  <body>
    <div class="container">
      <div class="row pt-3">
        <div class="col-md-8">
          <h1>
            <a href="/" style="text-decoration: none">Quotes to Scrape</a>
          </h1>
        </div>
        <div class="col-md-4">
          <p>
            <p>Welcome <b>{{ user.username }}!</b>
              {% if user.is_authenticated %}
              <img style="border-radius:50%; max-width: 50px;" 
              src="{{ user.profile.avatar.url }}" alt="avatar of user"/>
              {% endif %}
            </p>
              
            <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
            <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
            <a href="{% url 'users:logout' %}" class="btn btn-primary">logout</a>
          </p>
        </div>
      </div>
      {% block content%} {% endblock%}
    </div>
  </body>
</html>

dz_10/quotes/quoteapp/templates/quoteapp/detail_author.html
{% extends "quoteapp/base.html" %} {% load extract_tags %} {% block content %}

<h1>{{quote.author.fullname}}</h1>
<p>born date: <b>{{quote.author.born_date}}</b></p>
<p>born location: <b>{{quote.author.born_location}}</b></p>
<p>created at: <b>{{quote.author.created_at}}</b></p>
<p>Description: <b>{{quote.author.description}}</b></p>
{% endblock %}

dz_10/quotes/quoteapp/templates/quoteapp/detail_tag.html
{% extends "quoteapp/base.html" %} {% load extract_tags %} 
{% block content %}
{% for quote in quotes %}
<h1>{{quote.author.fullname}}</h1>
<p>{{quote.quote}}</p>
{% endfor%}
{% endblock %}

dz_10/quotes/quoteapp/templates/quoteapp/index.html
{% extends 'quoteapp/base.html' %}
{% load extract_tags %}
{% block content %}
<p>
    {% if user.is_authenticated %}
    <a href="{% url 'quoteapp:quote' %}" role="button" class="btn btn-primary">Add Quote</a>
    <a href="{% url 'quoteapp:author' %}" role="button" class="btn btn-primary">Add Author</a>
    <a href="{% url 'quoteapp:tag' %}" role="button" class="btn btn-primary">Add Tag</a>
    <a href="{% url 'users:profile' %}" role="button" class="btn btn-primary">Profile</a>
    {% endif %}
</p>
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
                <a href="{% url 'quoteapp:detail_author' quote.author_id %}">(about)</a>
                </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags|tags %}
                <a class="tag" href="{% url 'quoteapp:detail_tag' quote.id %}">{{tag.name}}</a>
                {% endfor%}
            </div>
            {% if user.is_admin %}
            <a href="{% url 'quoteapp:delete_quote' quote.id %}" role="button" class="btn btn-dark"> Delete </a>
            {% endif %}
        </div>
        {% endfor%}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif%}"
                        href="{% if quotes.has_previous %}{% url 'quoteapp:root_paginate' quotes.previous_page_number %}{%else%} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif%}" 
                        href="{% if quotes.has_next %}{% url 'quoteapp:root_paginate' quotes.next_page_number %}{%else%} # {% endif %}">
                        Next <span aria-hidden="true">→</span>
                    </a>
                </li>
            </ul>
        </nav>
        
    </div>
</div>
{% endblock %}

dz_10/quotes/quoteapp/templates/quoteapp/quote.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the quote:
            {{form.quote}}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label>Select author:
            <select name="author" required>
                {% for author in authors %}
                <option value="{{ author.id }}">{{ author.fullname }}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

dz_10/quotes/quoteapp/templates/quoteapp/tag.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}